- hosts: all
  vars:
  roles:
  - role: ANXS.oracle-jdk
    oracle_jdk_java_versions: 8
    oracle_jdk_java_version_default: 8
  - role: znzj.rbenv
    rbenv_ruby_version: 2.2.2
  - role: MagneDavidsen.gradle
    gradle_version: "2.7"
    oracle_jdk_java_versions: 8
    oracle_jdk_java_version_default: 8
  - cf_cli
  - configure_gocd
  - dot_net
